name: Release
on:
  push:
    branches:
      - "master"
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@904f3fef85a9c80a3750cbe7d5159268fd5caa9f
        with:
          ruby-version: '3.0.6'
      - name: Install dependencies
        run: bundle install
      - name: Build gem
        run: rake build
      - name: Build and publish to GitHub Package
        uses: actionshub/publish-gem-to-github@v1.0.6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          owner: rinsed-org
      - name: Build & Push to Rubygems
        run: |
          mkdir -p $HOME/.gem
          touch $HOME/.gem/credentials
          chmod 0600 $HOME/.gem/credentials
          printf -- "---\n:rubygems_api_key: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
          gem build *.gemspec
          gem push *.gem
        env:
          GEM_HOST_API_KEY: "${{secrets.RUBYGEMS_AUTH_TOKEN}}"

